return {
  api_errors = {
    [101] = 'Not enough rights to kick participant',
    [102] = 'USER_ADMIN_INVALID',
    [103] = 'method is available for supergroup chats only',
    [104] = 'Only creator of the group can kick administrators from the group',
    [105] = 'Bad Request: Need to be inviter of the user to kick it from the group',
    [106] = 'USER_NOT_PARTICIPANT',
    [107] = 'CHAT_ADMIN_REQUIRED',
    [108] = 'there is no administrators in the private chat',
    [110] = 'PEER_ID_INVALID',
    [111] = 'message is not modified',
    [112] = 'Can\'t parse message text: Can\'t find end of the entity starting at byte offset %d+',
    [113] = 'group chat is migrated to a supergroup chat',
    [114] = 'Message can\'t be forwarded',
    [115] = 'Message text is empty',
    [116] = 'message not found',
    [117] = 'chat not found',
    [118] = 'Message is too long',
    [119] = 'User not found',
    [120] = 'Can\'t parse reply keyboard markup JSON object',
    [121] = 'Field \\\"inline_keyboard\\\" of the InlineKeyboardMarkup should be an Array of Arrays',
    [122] = 'Can\'t parse inline keyboard button: InlineKeyboardButton should be an Object',
    [123] = 'Bad Request: Object expected as reply markup',
    [124] = 'QUERY_ID_INVALID',
    [125] = 'CHANNEL_PRIVATE',
    [126] = 'MESSAGE_TOO_LONG',
    [127] = 'wrong user_id specified',
    [128] = 'Too big total timeout [%d%.]+',
    [129] = 'BUTTON_DATA_INVALID',
    [130] = 'Type of file to send mismatch',
    [131] = 'MESSAGE_ID_INVALID',
    [403] = 'Bot was blocked by the user',
    [429] = 'Too many requests: retry later',
    [430] = 'Too big total timeout',
  }
}
